pipeline{
  agent any
  stages{
    stage('build login screen'){
      steps{
        build job : 'loign process build'
      }
    }
    
    stage('Deploy to Staging'){
      steps{
        build job : 'deploy to staging'
      }
    }
    
    
    stage('Deploy to production'){
      steps{
        build job : 'deploy to production'
      }
    }
    
    
  }
}